name: CI for Next.js

# Trigger this workflow on push to the main branch or when a pull request is created
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Permissions for the GitHub token
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js with caching
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"  # You can adjust the Node.js version if needed
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm ci  # Use 'npm ci' for clean installs in CI environments

      # Run linting (if you have ESLint configured)
      - name: Run Lint
        run: npm run lint

      # Run tests (if you have tests set up)
      - name: Run Tests
        run: npm test

      # Build the Next.js app
      - name: Build Next.js app
        run: npm run build

